version: '3.8'
services:
  azure-service-bus-message-hospital:
    build: .
    image: azure-service-bus-message-hospital
    container_name: azure-service-bus-message-hospital
    environment:
      AZURE_SERVICE_BUS_CONNECTION_STRING: ${AZURE_SERVICE_BUS_CONNECTION_STRING}
