version: '3.8'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  azure-service-bus-message-hospital:
    build:
      target: development
    image: azure-service-bus-message-hospital-development
    container_name: azure-service-bus-message-hospital-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./package.json:/home/node/package.json
