{{- include "helm-library.configmap" (list . "azure-service-bus-message-hospital.configmap") -}}
{{- define "azure-service-bus-message-hospital.configmap" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
{{- end -}}
