{{- include "helm-library.ingress" (list . "azure-service-bus-message-hospital.ingress") -}}
{{- define "azure-service-bus-message-hospital.ingress" -}}
metadata:
  annotations:
  {{- if .Values.ingress.host }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certIssuer }}
  {{- end }}
{{- end -}}
