{{- include "helm-library.secret" (list . "azure-service-bus-message-hospital.secret") -}}
{{- define "azure-service-bus-message-hospital.secret" -}}
data:
  AZURE_SERVICE_BUS_CONNECTION_STRING: {{ .Values.container.connectionString }}
{{- end -}}
